name: Deploy Node Backend to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.VPS_HOST }}
          username: tksultan
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          debug: true
          script: |
            set -e

            echo "Connected to VPS"
            whoami
            pwd

            echo "Going to backend directory"
            cd ~/backend-thrive

            echo "Syncing code with GitHub"
            git fetch origin
            git reset --hard origin/main
            git clean -fd

            echo "Installing dependencies"
            npm install --omit=dev

            echo "Reloading PM2"
            pm2 reload backend-thrive --update-env

            echo "Deploy completed successfully"
